version: '3'
services:
  alpine-glibc:
    build: alpine-glibc
    image: hamer/alpine-glibc
  subversion:
    build: subversion
    image: hamer/subversion
    environment:
      - SERVER_NAME=localhost
      - SSLCertificateFile=/certs/server.crt
      - SSLCertificateKeyFile=/certs/server.key
    volumes:
      - ./data/svn/certs:/certs
      - ./data/svn/repo:/var/svn
    ports:
      - "443:443"
      - "80:80"
